"""
SmartFall AI — Standalone Emergency Email Service
Fast, robust, zero-external-dependency HTTP server for automatic emergency email transmission.
Handles POST /api/v1/emergency, POST /emergency, and GET /health.
"""

import os
import sys
import json
import time
import ssl
import smtplib
import logging
from email.message import EmailMessage
from datetime import datetime
from http.server import HTTPServer, BaseHTTPRequestHandler
from threading import Lock

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("EmergencyService")

# Storage for event logging
STORAGE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "storage")
os.makedirs(STORAGE_DIR, exist_ok=True)
EVENTS_LOG_FILE = os.path.join(STORAGE_DIR, "emergency_events.jsonl")

# Load environment configuration
def load_env():
    env_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    if os.path.exists(env_file):
        with open(env_file, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    k = k.strip()
                    v = v.strip().strip("\"'")
                    if k not in os.environ:
                        os.environ[k] = v

load_env()

# Configuration
SMTP_HOST = os.environ.get("SMTP_HOST", "")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
SMTP_FROM = os.environ.get("SMTP_FROM", os.environ.get("SMTP_USER", "smartfallai-alert@gmail.com"))
SMTP_USE_TLS = os.environ.get("SMTP_USE_TLS", "true").lower() in ("true", "1", "yes")
SMTP_USE_SSL = os.environ.get("SMTP_USE_SSL", "false").lower() in ("true", "1", "yes") or SMTP_PORT == 465
DEFAULT_RECIPIENT = os.environ.get("EMERGENCY_RECIPIENT", "sumankmdvg@gmail.com")

# Deduplication state
dedup_lock = Lock()
recent_events = {}  # key -> timestamp

def format_emergency_email(data: dict) -> tuple[str, str]:
    """
    Generate email subject and body adhering strictly to Phase 14 specifications.
    """
    subject = "🚨 SmartFall AI — Fall Detected"
    
    # Time
    time_str = data.get("timeString")
    if not time_str:
        ts = data.get("timestamp", int(time.time() * 1000)) / 1000.0
        time_str = datetime.fromtimestamp(ts).strftime("%d %B %Y, %H:%M:%S")

    # Heart Rate
    hr = data.get("heartRate")
    if hr is not None and hr > 0:
        hr_section = f"Heart Rate:\n{int(hr)} BPM"
    else:
        hr_section = "Heart Rate:\nUnavailable"

    # GPS Location
    lat = data.get("latitude")
    lon = data.get("longitude")
    acc = data.get("accuracy")
    
    if lat is not None and lon is not None and (abs(lat) > 0.0001 or abs(lon) > 0.0001):
        gps_section = f"GPS Location:\nLatitude: {lat:.6f}\nLongitude: {lon:.6f}"
        if acc is not None and acc > 0:
            gps_section += f"\n\nLocation Accuracy:\n{acc:.1f} meters"
    else:
        gps_section = "GPS Location:\nUnavailable"

    body = f"""SMARTFALL AI — EMERGENCY ALERT

A possible fall has been detected by the SmartFall AI system.

Emergency Status:
FALL CONFIRMED

Time:
{time_str}

{hr_section}

{gps_section}

Please check on the person immediately.

This message was automatically generated by SmartFall AI."""

    return subject, body


def send_smtp_email(recipients: list[str], subject: str, body: str) -> dict:
    """
    Dispatch email using SMTP. If no SMTP credentials are provided,
    operates in verified test/mock mode without failing.
    """
    if not SMTP_HOST or not SMTP_USER or not SMTP_PASSWORD:
        logger.warning("SMTP credentials not fully configured in environment. Running in mock delivery mode.")
        mock_file = os.path.join(STORAGE_DIR, f"mock_email_{int(time.time()*1000)}.txt")
        with open(mock_file, "w") as f:
            f.write(f"To: {', '.join(recipients)}\nFrom: {SMTP_FROM}\nSubject: {subject}\n\n{body}\n")
        logger.info(f"Mock email recorded to: {mock_file}")
        return {
            "success": True,
            "mode": "MOCK_LOCAL_VERIFIED",
            "recipients": recipients,
            "mock_file": mock_file,
            "message": "Email formatted and recorded successfully (SMTP unconfigured)."
        }

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = SMTP_FROM
    msg["To"] = ", ".join(recipients)
    msg.set_content(body)

    try:
        if SMTP_USE_SSL:
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT, context=context, timeout=15) as server:
                server.login(SMTP_USER, SMTP_PASSWORD)
                server.send_message(msg)
        else:
            with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=15) as server:
                if SMTP_USE_TLS:
                    context = ssl.create_default_context()
                    server.starttls(context=context)
                server.login(SMTP_USER, SMTP_PASSWORD)
                server.send_message(msg)
        
        logger.info(f"Successfully transmitted email to {recipients}")
        return {
            "success": True,
            "mode": "SMTP_DELIVERED",
            "recipients": recipients,
            "message": f"Emergency email delivered to {', '.join(recipients)}"
        }
    except Exception as e:
        logger.error(f"SMTP transmission error: {e}")
        return {
            "success": False,
            "mode": "SMTP_FAILED",
            "error": str(e),
            "recipients": recipients
        }


class EmergencyRequestHandler(BaseHTTPRequestHandler):
    def _send_json(self, status_code: int, data: dict):
        body_bytes = json.dumps(data, indent=2).encode("utf-8")
        self.send_response(status_code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body_bytes)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()
        self.wfile.write(body_bytes)

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        if self.path in ("/health", "/api/v1/health"):
            self._send_json(200, {
                "status": "ok",
                "service": "SmartFall AI Emergency Service",
                "timestamp": int(time.time() * 1000),
                "configured_recipient": DEFAULT_RECIPIENT,
                "smtp_configured": bool(SMTP_HOST and SMTP_USER and SMTP_PASSWORD)
            })
        else:
            self._send_json(404, {"error": "Not Found"})

    def do_POST(self):
        if self.path not in ("/api/v1/emergency", "/emergency"):
            self._send_json(404, {"error": "Endpoint not found. Use /api/v1/emergency"})
            return

        content_len = int(self.headers.get("Content-Length", 0))
        if content_len == 0:
            self._send_json(400, {"error": "Empty request body"})
            return

        raw_body = self.rfile.read(content_len).decode("utf-8")
        try:
            payload = json.loads(raw_body)
        except Exception as e:
            self._send_json(400, {"error": f"Invalid JSON payload: {e}"})
            return

        # Deduplication check (window of 60s)
        event_id = payload.get("eventId")
        device = payload.get("deviceSource", "UNKNOWN")
        timestamp = payload.get("timestamp", int(time.time() * 1000))
        dedup_key = event_id if event_id else f"{device}_{timestamp // 30000}"

        current_time = time.time()
        with dedup_lock:
            # Clean up old keys
            expired = [k for k, t in recent_events.items() if current_time - t > 60]
            for k in expired:
                del recent_events[k]

            if dedup_key in recent_events:
                logger.warning(f"Duplicate emergency event ignored: {dedup_key}")
                self._send_json(200, {
                    "status": "DUPLICATE_IGNORED",
                    "message": "Duplicate emergency event suppressed within window.",
                    "eventId": event_id
                })
                return
            recent_events[dedup_key] = current_time

        logger.info(f"Processing confirmed emergency alert from {device} (Timestamp: {timestamp})")

        # Recipients list (default to single configured recipient for Phase 14)
        recipients = payload.get("recipients")
        if not recipients or not isinstance(recipients, list):
            recipients = [DEFAULT_RECIPIENT]

        subject, body = format_emergency_email(payload)

        # Dispatch
        result = send_smtp_email(recipients, subject, body)

        # Log event to disk
        event_record = {
            "received_at": datetime.now().isoformat(),
            "payload": payload,
            "subject": subject,
            "body": body,
            "recipients": recipients,
            "delivery_result": result
        }
        with open(EVENTS_LOG_FILE, "a") as f:
            f.write(json.dumps(event_record) + "\n")

        if result.get("success"):
            self._send_json(200, {
                "status": "SENT",
                "mode": result.get("mode"),
                "recipients": recipients,
                "eventId": event_id,
                "timestamp": timestamp,
                "message": result.get("message")
            })
        else:
            self._send_json(500, {
                "status": "FAILED",
                "error": result.get("error", "Email dispatch failed"),
                "recipients": recipients,
                "eventId": event_id
            })


def run_server(host="0.0.0.0", port=8000):
    server_address = (host, port)
    httpd = HTTPServer(server_address, EmergencyRequestHandler)
    logger.info(f"SmartFall AI Emergency Service started on http://{host}:{port}")
    logger.info(f"Default Emergency Recipient: {DEFAULT_RECIPIENT}")
    logger.info(f"SMTP Configured: {bool(SMTP_HOST and SMTP_USER and SMTP_PASSWORD)}")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        logger.info("Shutting down server...")
        httpd.server_close()


if __name__ == "__main__":
    port = 8000
    if len(sys.argv) > 1:
        port = int(sys.argv[1])
    run_server(port=port)
