"""
Tests for SmartFall AI Emergency Service
Verifies email formatting, GPS fallback, Heart Rate fallback, duplicate protection, and API response.
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from emergency_service import format_emergency_email, send_smtp_email, DEFAULT_RECIPIENT


class TestEmergencyService(unittest.TestCase):

    def test_email_formatting_full_data(self):
        data = {
            "event": "FALL_CONFIRMED",
            "timeString": "03 September 2026, 15:35:21",
            "heartRate": 82.0,
            "latitude": 14.459400,
            "longitude": 75.924000,
            "accuracy": 20.0
        }
        subject, body = format_emergency_email(data)
        
        self.assertEqual(subject, "🚨 SmartFall AI — Fall Detected")
        self.assertIn("SMARTFALL AI — EMERGENCY ALERT", body)
        self.assertIn("Emergency Status:\nFALL CONFIRMED", body)
        self.assertIn("Time:\n03 September 2026, 15:35:21", body)
        self.assertIn("Heart Rate:\n82 BPM", body)
        self.assertIn("GPS Location:\nLatitude: 14.459400\nLongitude: 75.924000", body)
        self.assertIn("Location Accuracy:\n20.0 meters", body)
        self.assertIn("Please check on the person immediately.", body)
        self.assertIn("This message was automatically generated by SmartFall AI.", body)

    def test_missing_gps_fallback(self):
        data = {
            "event": "FALL_CONFIRMED",
            "timeString": "03 September 2026, 15:35:21",
            "heartRate": 78.0,
            "latitude": 0.0,
            "longitude": 0.0
        }
        subject, body = format_emergency_email(data)
        
        self.assertIn("GPS Location:\nUnavailable", body)
        self.assertNotIn("0.000000", body)
        self.assertNotIn("0.0,", body)

    def test_missing_heart_rate_fallback(self):
        data = {
            "event": "FALL_CONFIRMED",
            "timeString": "03 September 2026, 15:35:21",
            "heartRate": -1.0,
            "latitude": 14.4594,
            "longitude": 75.9240,
            "accuracy": 15.0
        }
        subject, body = format_emergency_email(data)
        
        self.assertIn("Heart Rate:\nUnavailable", body)
        self.assertNotIn("0 BPM", body)
        self.assertNotIn("-1 BPM", body)

    def test_default_recipient(self):
        self.assertEqual(DEFAULT_RECIPIENT, "sumankmdvg@gmail.com")

    def test_mock_dispatch_without_smtp(self):
        # When SMTP credentials are empty, must succeed in MOCK_LOCAL_VERIFIED mode
        subject, body = format_emergency_email({
            "timeString": "03 September 2026, 15:35:21",
            "heartRate": 75.0,
            "latitude": 14.4594,
            "longitude": 75.9240
        })
        result = send_smtp_email([DEFAULT_RECIPIENT], subject, body)
        self.assertTrue(result["success"])
        self.assertIn(DEFAULT_RECIPIENT, result["recipients"])


if __name__ == "__main__":
    unittest.main()
