"""
Tests for SmartFall AI Emergency Service
Verifies email formatting, GPS fallback, Heart Rate fallback, duplicate protection, and API response.
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from emergency_service import format_emergency_email, send_smtp_email, get_smtp_config


class TestEmergencyService(unittest.TestCase):

    def test_email_formatting_full_data(self):
        data = {
            "event": "FALL_CONFIRMED",
            "timeString": "03 September 2026, 15:35:21",
            "heartRate": 82.0,
            "latitude": 14.459400,
            "longitude": 75.924000,
            "accuracy": 20.0
        }
        subject, body = format_emergency_email(data)
        
        self.assertEqual(subject, "🚨 SmartFall AI — Fall Detected")
        self.assertIn("SMARTFALL AI — EMERGENCY ALERT", body)
        self.assertIn("Emergency Status:\nFALL CONFIRMED", body)
        self.assertIn("Time:\n03 September 2026, 15:35:21", body)
        self.assertIn("Heart Rate:\n82 BPM", body)
        self.assertIn("GPS Location:\nLatitude: 14.459400\nLongitude: 75.924000", body)
        self.assertIn("Location Accuracy:\n20.0 meters", body)
        self.assertIn("Please check on the person immediately.", body)
        self.assertIn("This message was automatically generated by SmartFall AI.", body)

    def test_missing_gps_fallback(self):
        data = {
            "event": "FALL_CONFIRMED",
            "timeString": "03 September 2026, 15:35:21",
            "heartRate": 78.0,
            "latitude": 0.0,
            "longitude": 0.0
        }
        subject, body = format_emergency_email(data)
        
        self.assertIn("GPS Location:\nUnavailable", body)
        self.assertNotIn("0.000000", body)
        self.assertNotIn("0.0,", body)

    def test_missing_heart_rate_fallback(self):
        data = {
            "event": "FALL_CONFIRMED",
            "timeString": "03 September 2026, 15:35:21",
            "heartRate": -1.0,
            "latitude": 14.4594,
            "longitude": 75.9240,
            "accuracy": 15.0
        }
        subject, body = format_emergency_email(data)
        
        self.assertIn("Heart Rate:\nUnavailable", body)
        self.assertNotIn("0 BPM", body)
        self.assertNotIn("-1 BPM", body)

    def test_default_recipient(self):
        config = get_smtp_config(reload_file=False)
        self.assertEqual(config["recipient"], "sumankmdvg@gmail.com")

    def test_unconfigured_smtp_fails_clearly(self):
        from unittest.mock import patch
        with patch("emergency_service.get_smtp_config") as mock_cfg:
            mock_cfg.return_value = {
                "host": "smtp.gmail.com",
                "port": 587,
                "user": "",
                "password": "",
                "from": "SmartFall AI Alert <noreply@smartfallai.com>",
                "use_tls": True,
                "use_ssl": False,
                "recipient": "sumankmdvg@gmail.com",
                "configured": False
            }
            subject, body = format_emergency_email({
                "timeString": "03 September 2026, 15:35:21",
                "heartRate": 75.0,
                "latitude": 14.4594,
                "longitude": 75.9240
            })
            result = send_smtp_email(["sumankmdvg@gmail.com"], subject, body)
            self.assertFalse(result["success"])
            self.assertEqual(result["mode"], "SMTP_UNCONFIGURED")
            self.assertIn("SMTP_USER", result["error"])

    def test_authenticated_smtp_success(self):
        from unittest.mock import patch, MagicMock
        with patch("emergency_service.get_smtp_config") as mock_cfg, patch("smtplib.SMTP") as mock_smtp:
            mock_cfg.return_value = {
                "host": "smtp.gmail.com",
                "port": 587,
                "user": "testuser@gmail.com",
                "password": "test-app-password",
                "from": "SmartFall AI Alert <testuser@gmail.com>",
                "use_tls": True,
                "use_ssl": False,
                "recipient": "sumankmdvg@gmail.com",
                "configured": True
            }
            mock_server = MagicMock()
            mock_smtp.return_value.__enter__.return_value = mock_server
            mock_server.send_message.return_value = {}  # No rejections

            subject, body = format_emergency_email({
                "timeString": "03 September 2026, 15:35:21",
                "heartRate": 75.0
            })
            result = send_smtp_email(["sumankmdvg@gmail.com"], subject, body)
            self.assertTrue(result["success"])
            self.assertEqual(result["mode"], "SMTP_ACCEPTED")
            mock_server.starttls.assert_called_once()
            mock_server.login.assert_called_once_with("testuser@gmail.com", "test-app-password")
            mock_server.send_message.assert_called_once()


if __name__ == "__main__":
    unittest.main()
